spring:
  application:
    name: microservice-movie-ribbon

server:
  port: 7902

eureka:
  client:
    username: user
    password: password
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.client.username}:${eureka.client.password}@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
