server:
  port: 8761

eureka:
  instance:
    hostname: localhost           #hostname
    prefer-ip-address: true       #preferIpAddress
  client:
    register-with-eureka: false   #registerWithEureka，是否将自己注册到eureka server,
                                  #为false则表示作为服务端不注册到eureka server，为true则表示作为客户端注册到eureka server
    fetch-registry: false         #fetchRegistry,是否从eureka server获取注册信息（同步服务实例列表时）
    service-url:                  #serviceUrl
      defaultZone: http://localhost:${server.port}/eureka/            #defaultZone


